server:
  port: 5001
spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/airline_user_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  frontend-url: ${FRONTEND_URL:http://localhost:3000}
  mail-from: ${MAIL_FROM:no-reply@airline.local}

  jwt:
    secret: ${JWT_SECRET}
    access-token-expiration-ms: ${JWT_EXPIRATION:900000}
    refresh-token-expiration-days: ${REFRESH_TOKEN_EXPIRATION:7}

  tokens:
    email-verification-hours: 24
    password-reset-minutes: 30
